### ISSUE TITLE
Summarizing functions?

### ISSUE THREAD

**Issue by mo2561057** [OpenSourceEconomics/dcegm#1]
https://github.com/segsell/dc-egm/blob/937d093c115240cfbd6ff0996a19cedde706650c/src/egm_step.py#L74-L112

For both readability and more analytic structure I would summarize some of the functions here.
In particular I would put the following functions into:
- next_period_consumption
- next_period_marginal_utility
- rhs_euler     
- current_period_consumption
The new function could be called _map_exogenous_to_endogenous_grid and outputs would be current period consumption and endogenous_wealth grid.

**Comment by segsell** [comment]
Done! I summarized the functions above in ``map_exog_to_endog_grid()``. Thanks for the suggestion!
