### ISSUE TITLE
Get rhs euler as functio arg?

### ISSUE THREAD

**Issue by mo2561057** [OpenSourceEconomics/dcegm#6]
https://github.com/segsell/dc-egm/blob/a7de99c92664630621ee8a514848c247191a1a9e/src/egm_step.py#L117
Maybe this could be another argument. One step towards making choice of method more flexible?

**Comment by segsell** [comment]
Renamed to ``_calc_rhs_euler``. It is now an internal function of ``_get_current_period_consumption()``, which is in turn called by ``map_exog_to_endog_grid()``.
