### ISSUE TITLE
DC-EGM code

### ISSUE THREAD

**Issue by AMonninger** [OpenSourceEconomics/dcegm#60]
Hi everyone,
thanks for coding up FUES, it looks really good. I'm currently comparing different upper envelope algorithms (DC-EGM from Iskhakov) implemented in [econ-ark](https://github.com/econ-ark/DemARK/blob/master/notebooks/DCEGM-Upper-Envelope.ipynb), FUES implemented by [Akshay](https://github.com/akshayshanker/FUES_EGM/tree/main), and your version.

I found that the calculation of the intersection point is slightly different between your FUES version and DC-EGM in HARK. Could you provide me with the DC-EGM code you used?

Happy to talk more.
Best,
Adrian

**Comment by AMonninger** [comment]
You can find the comparison here:
https://github.com/AMonninger/REMARK_UpperEnvelopeComparison/blob/main/code/python/Example1_Writing_a_Will.ipynb

Happy to discuss and collaborate on that.

**Comment by segsell** [comment]
Hi Adrian,

thanks for your interest in our DC-EGM and upper envelope algorithms.
You'll find both in this GitHub repo <https://github.com/segsell/dc-egm/>.

We're happy to chat about our implementation with you. How about next
Thursday, July 27th, at 3 pm German time?

Best,
Sebastian

**Comment by MaxBlesch** [comment]
Thanks so much. We will close that issue now!
