### ISSUE TITLE
Speed up state space creation

### ISSUE THREAD

**Issue by segsell** [OpenSourceEconomics/dcegm#90]
Currently, the creation of large state spaces is very slow. 

To-Do:

- [x] Separate ```create_state_space``` from ```get_solve_function``` so that the state space can be created outside of ```jax```. E.g. with ```numba```
- [ ] If we want to use ```numba```, we need to switch from the options ```dict``` to ```namedtuple```

**Comment by MaxBlesch** [comment]
Done with moving away from the old per period creation.
